FROM rust:1.71.0 as builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM node:18.17-bullseye-slim as main
LABEL maintainer="Meet Vasani <lowkey-who@users.noreply.github.com>"
RUN apt-get update && apt-get install curl -y 
RUN curl -fsSL https://get.pulumi.com | bash
WORKDIR /app
COPY --from=builder /app/target/release/pulumi-actions /usr/bin/pulumi-actions
ENTRYPOINT ["/usr/bin/pulumi-actions"]